#  ┏┓┏┳┓┏┓┳┓┏┓┓┏┳┏┓  ┳┓┳┳┳┓┳┓┓ ┏┓
#  ┗┓ ┃ ┣┫┣┫┗┓┣┫┃┃┃━━┣┫┃┃┣┫┣┫┃ ┣ 
#  ┗┛ ┻ ┛┗┛┗┗┛┛┗┻┣┛  ┻┛┗┛┻┛┻┛┗┛┗┛
#                                



# whether to print print a new line at the start of the prompt
add_newline = true

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$shell$time$cmd_duration$directory $git_branch $git_status\n
$character
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[•   ](bold fg:green)"
error_symbol = "[•   ](bold fg:red)"
vimcmd_symbol = "[•   ](bold fg:green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


# Git stuffs
[git_branch]
style = "bg: green"
symbol = "󰘬"
truncation_length = 4
truncation_symbol = ""
format = "• [](bold fg:green)[$symbol $branch(:$remote_branch)](bold fg:black bg:green)[](bold fg:green)"

[git_status]
conflicted = " = "
ahead = " ⇡ "
behind = " ⇣ "
diverged = " ⇕ "
untracked = " ? "
stashed = " $ "
modified = " ! "
staged = "[+$count](fg:green)"
renamed = " » "
deleted = " ✘ "
format = "[$all_status$ahead_behind](bold fg:green)"

# Line Break
[line_break]
disabled = false


# Directory
[directory]
home_symbol = "  "
read_only = "  "
style = "bold bg:yellow fg:black"
truncation_length = 6
truncation_symbol = "••/"
format = '[](bold fg:yellow)[$path ]($style)[](bold fg:yellow)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "


# Cmd duration
[cmd_duration]
min_time = 0
format = '[](bold fg:green)[ $duration](bold bg:green fg:black)[](bold fg:green) •• '

# Time
[time]
disabled = false
time_format = "%R"
format = '[](bold fg:yellow)[󰥔 $time](bold bg:yellow fg:black)[](bold fg:yellow) •• '



# Shell
[shell]
disabled = false
fish_indicator = "󰈺 fish"
zsh_indicator = " zsh"
bash_indicator = "󱆃 bash"
format = '[](bold fg:green)[$indicator](bold bg:green fg:black)[](bold fg:green) •• '
