# Shell variables
# Generated by 'wal'
wallpaper="/home/ooximkool/Wallpapers/cabin-2.jpg"

# Special
background='#111618'
foreground='#c3c4c5'
cursor='#c3c4c5'

# Colors
color0='#111618'
color1='#AD877B'
color2='#9E7F80'
color3='#7C9682'
color4='#95A48D'
color5='#AFAE95'
color6='#B8BAA4'
color7='#c3c4c5'
color8='#5b6b70'
color9='#AD877B'
color10='#9E7F80'
color11='#7C9682'
color12='#95A48D'
color13='#AFAE95'
color14='#B8BAA4'
color15='#c3c4c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
