--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ooximkool/Wallpapers/cabin-2.jpg"

-- Special
background="#111618"
foreground="#c3c4c5"
cursor="#c3c4c5"

-- Colors
color0="#111618"
color1="#AD877B"
color2="#9E7F80"
color3="#7C9682"
color4="#95A48D"
color5="#AFAE95"
color6="#B8BAA4"
color7="#c3c4c5"
color8="#5b6b70"
color9="#AD877B"
color10="#9E7F80"
color11="#7C9682"
color12="#95A48D"
color13="#AFAE95"
color14="#B8BAA4"
color15="#c3c4c5"
